package com.ifeng.bigtrade.purchasing.mapper;

import com.ifeng.bigtrade.purchasing.entites.PApplicationDetail;
import com.ifeng.bigtrade.purchasing.entites.PApplicationDetailExample;
import com.ifeng.bigtrade.purchasing.vo.PApplicationDetailVO;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PApplicationDetailMapper
{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@SelectProvider(type = PApplicationDetailSqlProvider.class, method = "countByExample")
	long countByExample(PApplicationDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@DeleteProvider(type = PApplicationDetailSqlProvider.class, method = "deleteByExample")
	int deleteByExample(PApplicationDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@Delete(
	{ "delete from p_applicationdetail", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@Options(keyProperty = "id", useGeneratedKeys = true)
	@Insert(
	{ "insert into p_applicationdetail (id, addTime, ", "deleteStatus, commodityId, ", "firmId, issuanceplan_id, ",
			"count, totalAmount, ", "brokerage, status, ", "financeAccountId, startNo, ", "endNo, winCount)",
			"values (#{id,jdbcType=BIGINT}, #{addTime,jdbcType=TIMESTAMP}, ",
			"#{deleteStatus,jdbcType=BIT}, #{commodityId,jdbcType=BIGINT}, ",
			"#{firmId,jdbcType=BIGINT}, #{issuanceplan_id,jdbcType=BIGINT}, ",
			"#{count,jdbcType=INTEGER}, #{totalAmount,jdbcType=DECIMAL}, ",
			"#{brokerage,jdbcType=DECIMAL}, #{status,jdbcType=INTEGER}, ",
			"#{financeAccountId,jdbcType=BIGINT}, #{startNo,jdbcType=VARCHAR}, ",
			"#{endNo,jdbcType=VARCHAR}, #{winCount,jdbcType=INTEGER})" })
	int insert(PApplicationDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@Options(keyProperty = "id", useGeneratedKeys = true)
	@InsertProvider(type = PApplicationDetailSqlProvider.class, method = "insertSelective")
	int insertSelective(PApplicationDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@SelectProvider(type = PApplicationDetailSqlProvider.class, method = "selectByExample")
	@Results(
	{ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "addTime", property = "addTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "deleteStatus", property = "deleteStatus", jdbcType = JdbcType.BIT),
			@Result(column = "commodityId", property = "commodityId", jdbcType = JdbcType.BIGINT),
			@Result(column = "firmId", property = "firmId", jdbcType = JdbcType.BIGINT),
			@Result(column = "issuanceplan_id", property = "issuanceplan_id", jdbcType = JdbcType.BIGINT),
			@Result(column = "count", property = "count", jdbcType = JdbcType.INTEGER),
			@Result(column = "totalAmount", property = "totalAmount", jdbcType = JdbcType.DECIMAL),
			@Result(column = "brokerage", property = "brokerage", jdbcType = JdbcType.DECIMAL),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "financeAccountId", property = "financeAccountId", jdbcType = JdbcType.BIGINT),
			@Result(column = "startNo", property = "startNo", jdbcType = JdbcType.VARCHAR),
			@Result(column = "endNo", property = "endNo", jdbcType = JdbcType.VARCHAR),
			@Result(column = "winCount", property = "winCount", jdbcType = JdbcType.INTEGER) })
	List<PApplicationDetail> selectByExample(PApplicationDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@Select(
	{ "select", "id, addTime, deleteStatus, commodityId, firmId, issuanceplan_id, count, totalAmount, ",
			"brokerage, status, financeAccountId, startNo, endNo, winCount", "from p_applicationdetail",
			"where id = #{id,jdbcType=BIGINT}" })
	@Results(
	{ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "addTime", property = "addTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "deleteStatus", property = "deleteStatus", jdbcType = JdbcType.BIT),
			@Result(column = "commodityId", property = "commodityId", jdbcType = JdbcType.BIGINT),
			@Result(column = "firmId", property = "firmId", jdbcType = JdbcType.BIGINT),
			@Result(column = "issuanceplan_id", property = "issuanceplan_id", jdbcType = JdbcType.BIGINT),
			@Result(column = "count", property = "count", jdbcType = JdbcType.INTEGER),
			@Result(column = "totalAmount", property = "totalAmount", jdbcType = JdbcType.DECIMAL),
			@Result(column = "brokerage", property = "brokerage", jdbcType = JdbcType.DECIMAL),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
			@Result(column = "financeAccountId", property = "financeAccountId", jdbcType = JdbcType.BIGINT),
			@Result(column = "startNo", property = "startNo", jdbcType = JdbcType.VARCHAR),
			@Result(column = "endNo", property = "endNo", jdbcType = JdbcType.VARCHAR),
			@Result(column = "winCount", property = "winCount", jdbcType = JdbcType.INTEGER) })
	PApplicationDetail selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@UpdateProvider(type = PApplicationDetailSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") PApplicationDetail record,
			@Param("example") PApplicationDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@UpdateProvider(type = PApplicationDetailSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") PApplicationDetail record,
			@Param("example") PApplicationDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@UpdateProvider(type = PApplicationDetailSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(PApplicationDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_applicationdetail
	 * @mbg.generated  Wed Nov 01 18:57:40 CST 2017
	 */
	@Update(
	{ "update p_applicationdetail", "set addTime = #{addTime,jdbcType=TIMESTAMP},",
			"deleteStatus = #{deleteStatus,jdbcType=BIT},", "commodityId = #{commodityId,jdbcType=BIGINT},",
			"firmId = #{firmId,jdbcType=BIGINT},", "issuanceplan_id = #{issuanceplan_id,jdbcType=BIGINT},",
			"count = #{count,jdbcType=INTEGER},", "totalAmount = #{totalAmount,jdbcType=DECIMAL},",
			"brokerage = #{brokerage,jdbcType=DECIMAL},", "status = #{status,jdbcType=INTEGER},",
			"financeAccountId = #{financeAccountId,jdbcType=BIGINT},", "startNo = #{startNo,jdbcType=VARCHAR},",
			"endNo = #{endNo,jdbcType=VARCHAR},", "winCount = #{winCount,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(PApplicationDetail record);

	/**************** next add *******************/
	@Select(
	{ "select", "sum(count)", "from p_applicationdetail", "where issuanceplan_id = #{id,jdbcType=BIGINT}" })
	@ResultType(Integer.class)
	int countSumByIssuanceplanId(@Param("id") Long id);

	@Select(
	{ "select", "id, addTime, deleteStatus, commodityId, firmId, issuanceplan_id, count, totalAmount, ",
			"brokerage, status, financeAccountId, startNo, endNo,winCount", "from p_applicationdetail",
			"where issuanceplan_id = #{planid,jdbcType=BIGINT} and status=4 order by startNo asc" })
	@ResultType(PApplicationDetail.class)
	List<PApplicationDetail> selectForLotterSystem(@Param("planid") Long planid);
	
	@SelectProvider(type = PApplicationDetailSqlProvider.class, method = "selectVOByUseridInStatus")
	@ResultType(PApplicationDetailVO.class)
	List<PApplicationDetailVO> selectVOByUseridInStatus(Long userid,String status);
}