package com.ifeng.bigtrade.purchasing.mapper;

import com.ifeng.bigtrade.purchasing.entites.PFailedPlan;
import com.ifeng.bigtrade.purchasing.entites.PFailedPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PFailedPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @SelectProvider(type=PFailedPlanSqlProvider.class, method="countByExample")
    long countByExample(PFailedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @DeleteProvider(type=PFailedPlanSqlProvider.class, method="deleteByExample")
    int deleteByExample(PFailedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @Delete({
        "delete from p_failedplan",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @Insert({
        "insert into p_failedplan (id, issuanceplan_id, ",
        "operatorId, operatorName, ",
        "operatorIp)",
        "values (#{id,jdbcType=BIGINT}, #{issuanceplan_id,jdbcType=BIGINT}, ",
        "#{operatorId,jdbcType=BIGINT}, #{operatorName,jdbcType=VARCHAR}, ",
        "#{operatorIp,jdbcType=VARCHAR})"
    })
    int insert(PFailedPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @InsertProvider(type=PFailedPlanSqlProvider.class, method="insertSelective")
    int insertSelective(PFailedPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @SelectProvider(type=PFailedPlanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="issuanceplan_id", property="issuanceplan_id", jdbcType=JdbcType.BIGINT),
        @Result(column="operatorId", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="operatorName", property="operatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="operatorIp", property="operatorIp", jdbcType=JdbcType.VARCHAR)
    })
    List<PFailedPlan> selectByExample(PFailedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @Select({
        "select",
        "id, issuanceplan_id, operatorId, operatorName, operatorIp",
        "from p_failedplan",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="issuanceplan_id", property="issuanceplan_id", jdbcType=JdbcType.BIGINT),
        @Result(column="operatorId", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="operatorName", property="operatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="operatorIp", property="operatorIp", jdbcType=JdbcType.VARCHAR)
    })
    PFailedPlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @UpdateProvider(type=PFailedPlanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PFailedPlan record, @Param("example") PFailedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @UpdateProvider(type=PFailedPlanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PFailedPlan record, @Param("example") PFailedPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @UpdateProvider(type=PFailedPlanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PFailedPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_failedplan
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    @Update({
        "update p_failedplan",
        "set issuanceplan_id = #{issuanceplan_id,jdbcType=BIGINT},",
          "operatorId = #{operatorId,jdbcType=BIGINT},",
          "operatorName = #{operatorName,jdbcType=VARCHAR},",
          "operatorIp = #{operatorIp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PFailedPlan record);
}