package com.ifeng.bigtrade.purchasing.mapper;

import com.ifeng.bigtrade.purchasing.entites.PLotteryResultDetail;
import com.ifeng.bigtrade.purchasing.entites.PLotteryResultDetailExample.Criteria;
import com.ifeng.bigtrade.purchasing.entites.PLotteryResultDetailExample.Criterion;
import com.ifeng.bigtrade.purchasing.entites.PLotteryResultDetailExample;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PLotteryResultDetailSqlProvider
{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String countByExample(PLotteryResultDetailExample example)
	{
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("p_lotteryresult_detail");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String deleteByExample(PLotteryResultDetailExample example)
	{
		SQL sql = new SQL();
		sql.DELETE_FROM("p_lotteryresult_detail");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String insertSelective(PLotteryResultDetail record)
	{
		SQL sql = new SQL();
		sql.INSERT_INTO("p_lotteryresult_detail");

		if (record.getId() != null)
		{
			sql.VALUES("id", "#{id,jdbcType=BIGINT}");
		}

		if (record.getAddTime() != null)
		{
			sql.VALUES("addTime", "#{addTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteStatus() != null)
		{
			sql.VALUES("deleteStatus", "#{deleteStatus,jdbcType=BIT}");
		}

		if (record.getIssuanceplan_id() != null)
		{
			sql.VALUES("issuanceplan_id", "#{issuanceplan_id,jdbcType=BIGINT}");
		}

		if (record.getWinningNo() != null)
		{
			sql.VALUES("winningNo", "#{winningNo,jdbcType=VARCHAR}");
		}

		if (record.getApplicationdetail_id() != null)
		{
			sql.VALUES("applicationdetail_id", "#{applicationdetail_id,jdbcType=BIGINT}");
		}

		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String selectByExample(PLotteryResultDetailExample example)
	{
		SQL sql = new SQL();
		if (example != null && example.isDistinct())
		{
			sql.SELECT_DISTINCT("id");
		} else
		{
			sql.SELECT("id");
		}
		sql.SELECT("addTime");
		sql.SELECT("deleteStatus");
		sql.SELECT("issuanceplan_id");
		sql.SELECT("winningNo");
		sql.SELECT("applicationdetail_id");
		sql.FROM("p_lotteryresult_detail");
		applyWhere(sql, example, false);

		if (example != null && example.getOrderByClause() != null)
		{
			sql.ORDER_BY(example.getOrderByClause());
		}

		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String updateByExampleSelective(Map<String, Object> parameter)
	{
		PLotteryResultDetail record = (PLotteryResultDetail) parameter.get("record");
		PLotteryResultDetailExample example = (PLotteryResultDetailExample) parameter.get("example");

		SQL sql = new SQL();
		sql.UPDATE("p_lotteryresult_detail");

		if (record.getId() != null)
		{
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}

		if (record.getAddTime() != null)
		{
			sql.SET("addTime = #{record.addTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteStatus() != null)
		{
			sql.SET("deleteStatus = #{record.deleteStatus,jdbcType=BIT}");
		}

		if (record.getIssuanceplan_id() != null)
		{
			sql.SET("issuanceplan_id = #{record.issuanceplan_id,jdbcType=BIGINT}");
		}

		if (record.getWinningNo() != null)
		{
			sql.SET("winningNo = #{record.winningNo,jdbcType=VARCHAR}");
		}

		if (record.getApplicationdetail_id() != null)
		{
			sql.SET("applicationdetail_id = #{record.applicationdetail_id,jdbcType=BIGINT}");
		}

		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String updateByExample(Map<String, Object> parameter)
	{
		SQL sql = new SQL();
		sql.UPDATE("p_lotteryresult_detail");

		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("addTime = #{record.addTime,jdbcType=TIMESTAMP}");
		sql.SET("deleteStatus = #{record.deleteStatus,jdbcType=BIT}");
		sql.SET("issuanceplan_id = #{record.issuanceplan_id,jdbcType=BIGINT}");
		sql.SET("winningNo = #{record.winningNo,jdbcType=VARCHAR}");
		sql.SET("applicationdetail_id = #{record.applicationdetail_id,jdbcType=BIGINT}");

		PLotteryResultDetailExample example = (PLotteryResultDetailExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	public String updateByPrimaryKeySelective(PLotteryResultDetail record)
	{
		SQL sql = new SQL();
		sql.UPDATE("p_lotteryresult_detail");

		if (record.getAddTime() != null)
		{
			sql.SET("addTime = #{addTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteStatus() != null)
		{
			sql.SET("deleteStatus = #{deleteStatus,jdbcType=BIT}");
		}

		if (record.getIssuanceplan_id() != null)
		{
			sql.SET("issuanceplan_id = #{issuanceplan_id,jdbcType=BIGINT}");
		}

		if (record.getWinningNo() != null)
		{
			sql.SET("winningNo = #{winningNo,jdbcType=VARCHAR}");
		}

		if (record.getApplicationdetail_id() != null)
		{
			sql.SET("applicationdetail_id = #{applicationdetail_id,jdbcType=BIGINT}");
		}

		sql.WHERE("id = #{id,jdbcType=BIGINT}");

		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table p_lotteryresult_detail
	 *
	 * @mbg.generated Tue Sep 12 13:39:42 CST 2017
	 */
	protected void applyWhere(SQL sql, PLotteryResultDetailExample example, boolean includeExamplePhrase)
	{
		if (example == null)
		{
			return;
		}

		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase)
		{
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else
		{
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}

		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++)
		{
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid())
			{
				if (firstCriteria)
				{
					firstCriteria = false;
				} else
				{
					sb.append(" or ");
				}

				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++)
				{
					Criterion criterion = criterions.get(j);
					if (firstCriterion)
					{
						firstCriterion = false;
					} else
					{
						sb.append(" and ");
					}

					if (criterion.isNoValue())
					{
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue())
					{
						if (criterion.getTypeHandler() == null)
						{
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else
						{
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue())
					{
						if (criterion.getTypeHandler() == null)
						{
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else
						{
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue())
					{
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++)
						{
							if (comma)
							{
								sb.append(", ");
							} else
							{
								comma = true;
							}
							if (criterion.getTypeHandler() == null)
							{
								sb.append(String.format(parmPhrase3, i, j, k));
							} else
							{
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}

		if (sb.length() > 0)
		{
			sql.WHERE(sb.toString());
		}
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public String insertBatch(Map map)
	{
		List<PLotteryResultDetail> list = (List<PLotteryResultDetail>) map.get("list");
		String nowTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
		StringBuffer sql = new StringBuffer();
		sql.append(
				"insert into p_lotteryresult_detail (addTime,deleteStatus,issuanceplan_id,winningNo,applicationdetail_id) ");
		sql.append("values ");
		for (int i = 0; i < list.size(); i++)
		{
			PLotteryResultDetail detail = list.get(i);
			sql.append("(");
			sql.append("'"+nowTime+"',");
			sql.append(detail.getDeleteStatus() + ",");
			sql.append(detail.getIssuanceplan_id() + ",");
			sql.append("'"+detail.getWinningNo() + "',");
			sql.append(detail.getApplicationdetail_id());
			sql.append(")");
			if (i != list.size() - 1)
			{
				sql.append(",");
			}
		}
		return sql.toString();
	}
}