package com.ifeng.bigtrade.purchasing.mapper;

import com.ifeng.bigtrade.purchasing.entites.PLotteryResultDetail;
import com.ifeng.bigtrade.purchasing.entites.PLotteryResultDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PLotteryResultDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @SelectProvider(type=PLotteryResultDetailSqlProvider.class, method="countByExample")
    long countByExample(PLotteryResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @DeleteProvider(type=PLotteryResultDetailSqlProvider.class, method="deleteByExample")
    int deleteByExample(PLotteryResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @Delete({
        "delete from p_lotteryresult_detail",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @Insert({
        "insert into p_lotteryresult_detail (id, addTime, ",
        "deleteStatus, issuanceplan_id, ",
        "winningNo, applicationdetail_id)",
        "values (#{id,jdbcType=BIGINT}, #{addTime,jdbcType=TIMESTAMP}, ",
        "#{deleteStatus,jdbcType=BIT}, #{issuanceplan_id,jdbcType=BIGINT}, ",
        "#{winningNo,jdbcType=VARCHAR}, #{applicationdetail_id,jdbcType=BIGINT})"
    })
    int insert(PLotteryResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @InsertProvider(type=PLotteryResultDetailSqlProvider.class, method="insertSelective")
    int insertSelective(PLotteryResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @SelectProvider(type=PLotteryResultDetailSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="addTime", property="addTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleteStatus", property="deleteStatus", jdbcType=JdbcType.BIT),
        @Result(column="issuanceplan_id", property="issuanceplan_id", jdbcType=JdbcType.BIGINT),
        @Result(column="winningNo", property="winningNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="applicationdetail_id", property="applicationdetail_id", jdbcType=JdbcType.BIGINT)
    })
    List<PLotteryResultDetail> selectByExample(PLotteryResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @Select({
        "select",
        "id, addTime, deleteStatus, issuanceplan_id, winningNo, applicationdetail_id",
        "from p_lotteryresult_detail",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="addTime", property="addTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleteStatus", property="deleteStatus", jdbcType=JdbcType.BIT),
        @Result(column="issuanceplan_id", property="issuanceplan_id", jdbcType=JdbcType.BIGINT),
        @Result(column="winningNo", property="winningNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="applicationdetail_id", property="applicationdetail_id", jdbcType=JdbcType.BIGINT)
    })
    PLotteryResultDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @UpdateProvider(type=PLotteryResultDetailSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PLotteryResultDetail record, @Param("example") PLotteryResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @UpdateProvider(type=PLotteryResultDetailSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PLotteryResultDetail record, @Param("example") PLotteryResultDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @UpdateProvider(type=PLotteryResultDetailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PLotteryResultDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_lotteryresult_detail
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    @Update({
        "update p_lotteryresult_detail",
        "set addTime = #{addTime,jdbcType=TIMESTAMP},",
          "deleteStatus = #{deleteStatus,jdbcType=BIT},",
          "issuanceplan_id = #{issuanceplan_id,jdbcType=BIGINT},",
          "winningNo = #{winningNo,jdbcType=VARCHAR},",
          "applicationdetail_id = #{applicationdetail_id,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PLotteryResultDetail record);
    
    /*****************next new add********************/
    @InsertProvider(type=PLotteryResultDetailSqlProvider.class, method="insertBatch")
    int insertBatch(@Param("list")List<PLotteryResultDetail> list);
}