package com.ifeng.bigtrade.finance.entites;

import java.math.BigDecimal;
import java.util.Date;

public class FAccountBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.id
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.addTime
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.deleteStatus
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private Boolean deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.amount
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.b_date
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private Date b_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.contractNo
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private String contractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.creditCode
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.debitCode
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private String debitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.summary
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.summaryNo
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private String summaryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_accountbook.voucher_id
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    private Long voucher_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.id
     *
     * @return the value of f_accountbook.id
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.id
     *
     * @param id the value for f_accountbook.id
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.addTime
     *
     * @return the value of f_accountbook.addTime
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.addTime
     *
     * @param addTime the value for f_accountbook.addTime
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.deleteStatus
     *
     * @return the value of f_accountbook.deleteStatus
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.deleteStatus
     *
     * @param deleteStatus the value for f_accountbook.deleteStatus
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.amount
     *
     * @return the value of f_accountbook.amount
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.amount
     *
     * @param amount the value for f_accountbook.amount
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.b_date
     *
     * @return the value of f_accountbook.b_date
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public Date getB_date() {
        return b_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.b_date
     *
     * @param b_date the value for f_accountbook.b_date
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setB_date(Date b_date) {
        this.b_date = b_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.contractNo
     *
     * @return the value of f_accountbook.contractNo
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.contractNo
     *
     * @param contractNo the value for f_accountbook.contractNo
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.creditCode
     *
     * @return the value of f_accountbook.creditCode
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.creditCode
     *
     * @param creditCode the value for f_accountbook.creditCode
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.debitCode
     *
     * @return the value of f_accountbook.debitCode
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public String getDebitCode() {
        return debitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.debitCode
     *
     * @param debitCode the value for f_accountbook.debitCode
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setDebitCode(String debitCode) {
        this.debitCode = debitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.summary
     *
     * @return the value of f_accountbook.summary
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.summary
     *
     * @param summary the value for f_accountbook.summary
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.summaryNo
     *
     * @return the value of f_accountbook.summaryNo
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public String getSummaryNo() {
        return summaryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.summaryNo
     *
     * @param summaryNo the value for f_accountbook.summaryNo
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setSummaryNo(String summaryNo) {
        this.summaryNo = summaryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_accountbook.voucher_id
     *
     * @return the value of f_accountbook.voucher_id
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public Long getVoucher_id() {
        return voucher_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_accountbook.voucher_id
     *
     * @param voucher_id the value for f_accountbook.voucher_id
     *
     * @mbg.generated Wed Aug 23 18:05:52 CST 2017
     */
    public void setVoucher_id(Long voucher_id) {
        this.voucher_id = voucher_id;
    }
}