package com.ifeng.bigtrade.finance.entites;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FDailyBalanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public FDailyBalanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("addTime is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("addTime is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("addTime =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("addTime <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("addTime >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("addTime >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("addTime <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("addTime <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("addTime in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("addTime not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("addTime between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("addTime not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNull() {
            addCriterion("deleteStatus is null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNotNull() {
            addCriterion("deleteStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusEqualTo(Boolean value) {
            addCriterion("deleteStatus =", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotEqualTo(Boolean value) {
            addCriterion("deleteStatus <>", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThan(Boolean value) {
            addCriterion("deleteStatus >", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleteStatus >=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThan(Boolean value) {
            addCriterion("deleteStatus <", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("deleteStatus <=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIn(List<Boolean> values) {
            addCriterion("deleteStatus in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotIn(List<Boolean> values) {
            addCriterion("deleteStatus not in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("deleteStatus between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleteStatus not between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCodeIsNull() {
            addCriterion("accountCode is null");
            return (Criteria) this;
        }

        public Criteria andAccountCodeIsNotNull() {
            addCriterion("accountCode is not null");
            return (Criteria) this;
        }

        public Criteria andAccountCodeEqualTo(String value) {
            addCriterion("accountCode =", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotEqualTo(String value) {
            addCriterion("accountCode <>", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeGreaterThan(String value) {
            addCriterion("accountCode >", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeGreaterThanOrEqualTo(String value) {
            addCriterion("accountCode >=", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeLessThan(String value) {
            addCriterion("accountCode <", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeLessThanOrEqualTo(String value) {
            addCriterion("accountCode <=", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeLike(String value) {
            addCriterion("accountCode like", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotLike(String value) {
            addCriterion("accountCode not like", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeIn(List<String> values) {
            addCriterion("accountCode in", values, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotIn(List<String> values) {
            addCriterion("accountCode not in", values, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeBetween(String value1, String value2) {
            addCriterion("accountCode between", value1, value2, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotBetween(String value1, String value2) {
            addCriterion("accountCode not between", value1, value2, "accountCode");
            return (Criteria) this;
        }

        public Criteria andB_dateIsNull() {
            addCriterion("b_date is null");
            return (Criteria) this;
        }

        public Criteria andB_dateIsNotNull() {
            addCriterion("b_date is not null");
            return (Criteria) this;
        }

        public Criteria andB_dateEqualTo(Date value) {
            addCriterion("b_date =", value, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateNotEqualTo(Date value) {
            addCriterion("b_date <>", value, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateGreaterThan(Date value) {
            addCriterion("b_date >", value, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("b_date >=", value, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateLessThan(Date value) {
            addCriterion("b_date <", value, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateLessThanOrEqualTo(Date value) {
            addCriterion("b_date <=", value, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateIn(List<Date> values) {
            addCriterion("b_date in", values, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateNotIn(List<Date> values) {
            addCriterion("b_date not in", values, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateBetween(Date value1, Date value2) {
            addCriterion("b_date between", value1, value2, "b_date");
            return (Criteria) this;
        }

        public Criteria andB_dateNotBetween(Date value1, Date value2) {
            addCriterion("b_date not between", value1, value2, "b_date");
            return (Criteria) this;
        }

        public Criteria andCreditAmountIsNull() {
            addCriterion("creditAmount is null");
            return (Criteria) this;
        }

        public Criteria andCreditAmountIsNotNull() {
            addCriterion("creditAmount is not null");
            return (Criteria) this;
        }

        public Criteria andCreditAmountEqualTo(BigDecimal value) {
            addCriterion("creditAmount =", value, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountNotEqualTo(BigDecimal value) {
            addCriterion("creditAmount <>", value, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountGreaterThan(BigDecimal value) {
            addCriterion("creditAmount >", value, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("creditAmount >=", value, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountLessThan(BigDecimal value) {
            addCriterion("creditAmount <", value, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("creditAmount <=", value, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountIn(List<BigDecimal> values) {
            addCriterion("creditAmount in", values, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountNotIn(List<BigDecimal> values) {
            addCriterion("creditAmount not in", values, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("creditAmount between", value1, value2, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andCreditAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("creditAmount not between", value1, value2, "creditAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountIsNull() {
            addCriterion("debitAmount is null");
            return (Criteria) this;
        }

        public Criteria andDebitAmountIsNotNull() {
            addCriterion("debitAmount is not null");
            return (Criteria) this;
        }

        public Criteria andDebitAmountEqualTo(BigDecimal value) {
            addCriterion("debitAmount =", value, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountNotEqualTo(BigDecimal value) {
            addCriterion("debitAmount <>", value, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountGreaterThan(BigDecimal value) {
            addCriterion("debitAmount >", value, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("debitAmount >=", value, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountLessThan(BigDecimal value) {
            addCriterion("debitAmount <", value, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("debitAmount <=", value, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountIn(List<BigDecimal> values) {
            addCriterion("debitAmount in", values, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountNotIn(List<BigDecimal> values) {
            addCriterion("debitAmount not in", values, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("debitAmount between", value1, value2, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andDebitAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("debitAmount not between", value1, value2, "debitAmount");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceIsNull() {
            addCriterion("lastdayBalance is null");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceIsNotNull() {
            addCriterion("lastdayBalance is not null");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceEqualTo(BigDecimal value) {
            addCriterion("lastdayBalance =", value, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceNotEqualTo(BigDecimal value) {
            addCriterion("lastdayBalance <>", value, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceGreaterThan(BigDecimal value) {
            addCriterion("lastdayBalance >", value, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lastdayBalance >=", value, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceLessThan(BigDecimal value) {
            addCriterion("lastdayBalance <", value, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lastdayBalance <=", value, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceIn(List<BigDecimal> values) {
            addCriterion("lastdayBalance in", values, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceNotIn(List<BigDecimal> values) {
            addCriterion("lastdayBalance not in", values, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lastdayBalance between", value1, value2, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andLastdayBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lastdayBalance not between", value1, value2, "lastdayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceIsNull() {
            addCriterion("todayBalance is null");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceIsNotNull() {
            addCriterion("todayBalance is not null");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceEqualTo(BigDecimal value) {
            addCriterion("todayBalance =", value, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceNotEqualTo(BigDecimal value) {
            addCriterion("todayBalance <>", value, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceGreaterThan(BigDecimal value) {
            addCriterion("todayBalance >", value, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("todayBalance >=", value, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceLessThan(BigDecimal value) {
            addCriterion("todayBalance <", value, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("todayBalance <=", value, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceIn(List<BigDecimal> values) {
            addCriterion("todayBalance in", values, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceNotIn(List<BigDecimal> values) {
            addCriterion("todayBalance not in", values, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("todayBalance between", value1, value2, "todayBalance");
            return (Criteria) this;
        }

        public Criteria andTodayBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("todayBalance not between", value1, value2, "todayBalance");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f_dailybalance
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 23 18:06:10 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f_dailybalance
     *
     * @mbg.generated Wed Aug 23 18:06:10 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}