package com.ifeng.bigtrade.finance.entites;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FSummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public FSummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("addTime is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("addTime is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("addTime =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("addTime <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("addTime >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("addTime >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("addTime <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("addTime <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("addTime in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("addTime not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("addTime between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("addTime not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNull() {
            addCriterion("deleteStatus is null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNotNull() {
            addCriterion("deleteStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusEqualTo(Boolean value) {
            addCriterion("deleteStatus =", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotEqualTo(Boolean value) {
            addCriterion("deleteStatus <>", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThan(Boolean value) {
            addCriterion("deleteStatus >", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleteStatus >=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThan(Boolean value) {
            addCriterion("deleteStatus <", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("deleteStatus <=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIn(List<Boolean> values) {
            addCriterion("deleteStatus in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotIn(List<Boolean> values) {
            addCriterion("deleteStatus not in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("deleteStatus between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleteStatus not between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andCanDeleteIsNull() {
            addCriterion("canDelete is null");
            return (Criteria) this;
        }

        public Criteria andCanDeleteIsNotNull() {
            addCriterion("canDelete is not null");
            return (Criteria) this;
        }

        public Criteria andCanDeleteEqualTo(Boolean value) {
            addCriterion("canDelete =", value, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteNotEqualTo(Boolean value) {
            addCriterion("canDelete <>", value, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteGreaterThan(Boolean value) {
            addCriterion("canDelete >", value, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("canDelete >=", value, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteLessThan(Boolean value) {
            addCriterion("canDelete <", value, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("canDelete <=", value, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteIn(List<Boolean> values) {
            addCriterion("canDelete in", values, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteNotIn(List<Boolean> values) {
            addCriterion("canDelete not in", values, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("canDelete between", value1, value2, "canDelete");
            return (Criteria) this;
        }

        public Criteria andCanDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("canDelete not between", value1, value2, "canDelete");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsIsNull() {
            addCriterion("isUserFunds is null");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsIsNotNull() {
            addCriterion("isUserFunds is not null");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsEqualTo(Boolean value) {
            addCriterion("isUserFunds =", value, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsNotEqualTo(Boolean value) {
            addCriterion("isUserFunds <>", value, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsGreaterThan(Boolean value) {
            addCriterion("isUserFunds >", value, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isUserFunds >=", value, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsLessThan(Boolean value) {
            addCriterion("isUserFunds <", value, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsLessThanOrEqualTo(Boolean value) {
            addCriterion("isUserFunds <=", value, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsIn(List<Boolean> values) {
            addCriterion("isUserFunds in", values, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsNotIn(List<Boolean> values) {
            addCriterion("isUserFunds not in", values, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsBetween(Boolean value1, Boolean value2) {
            addCriterion("isUserFunds between", value1, value2, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andIsUserFundsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isUserFunds not between", value1, value2, "isUserFunds");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNoIsNull() {
            addCriterion("summaryNo is null");
            return (Criteria) this;
        }

        public Criteria andSummaryNoIsNotNull() {
            addCriterion("summaryNo is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryNoEqualTo(String value) {
            addCriterion("summaryNo =", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoNotEqualTo(String value) {
            addCriterion("summaryNo <>", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoGreaterThan(String value) {
            addCriterion("summaryNo >", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoGreaterThanOrEqualTo(String value) {
            addCriterion("summaryNo >=", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoLessThan(String value) {
            addCriterion("summaryNo <", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoLessThanOrEqualTo(String value) {
            addCriterion("summaryNo <=", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoLike(String value) {
            addCriterion("summaryNo like", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoNotLike(String value) {
            addCriterion("summaryNo not like", value, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoIn(List<String> values) {
            addCriterion("summaryNo in", values, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoNotIn(List<String> values) {
            addCriterion("summaryNo not in", values, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoBetween(String value1, String value2) {
            addCriterion("summaryNo between", value1, value2, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andSummaryNoNotBetween(String value1, String value2) {
            addCriterion("summaryNo not between", value1, value2, "summaryNo");
            return (Criteria) this;
        }

        public Criteria andLedger_idIsNull() {
            addCriterion("ledger_id is null");
            return (Criteria) this;
        }

        public Criteria andLedger_idIsNotNull() {
            addCriterion("ledger_id is not null");
            return (Criteria) this;
        }

        public Criteria andLedger_idEqualTo(Long value) {
            addCriterion("ledger_id =", value, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idNotEqualTo(Long value) {
            addCriterion("ledger_id <>", value, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idGreaterThan(Long value) {
            addCriterion("ledger_id >", value, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idGreaterThanOrEqualTo(Long value) {
            addCriterion("ledger_id >=", value, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idLessThan(Long value) {
            addCriterion("ledger_id <", value, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idLessThanOrEqualTo(Long value) {
            addCriterion("ledger_id <=", value, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idIn(List<Long> values) {
            addCriterion("ledger_id in", values, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idNotIn(List<Long> values) {
            addCriterion("ledger_id not in", values, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idBetween(Long value1, Long value2) {
            addCriterion("ledger_id between", value1, value2, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andLedger_idNotBetween(Long value1, Long value2) {
            addCriterion("ledger_id not between", value1, value2, "ledger_id");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagIsNull() {
            addCriterion("fundDCFlag is null");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagIsNotNull() {
            addCriterion("fundDCFlag is not null");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagEqualTo(String value) {
            addCriterion("fundDCFlag =", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagNotEqualTo(String value) {
            addCriterion("fundDCFlag <>", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagGreaterThan(String value) {
            addCriterion("fundDCFlag >", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagGreaterThanOrEqualTo(String value) {
            addCriterion("fundDCFlag >=", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagLessThan(String value) {
            addCriterion("fundDCFlag <", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagLessThanOrEqualTo(String value) {
            addCriterion("fundDCFlag <=", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagLike(String value) {
            addCriterion("fundDCFlag like", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagNotLike(String value) {
            addCriterion("fundDCFlag not like", value, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagIn(List<String> values) {
            addCriterion("fundDCFlag in", values, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagNotIn(List<String> values) {
            addCriterion("fundDCFlag not in", values, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagBetween(String value1, String value2) {
            addCriterion("fundDCFlag between", value1, value2, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andFundDCFlagNotBetween(String value1, String value2) {
            addCriterion("fundDCFlag not between", value1, value2, "fundDCFlag");
            return (Criteria) this;
        }

        public Criteria andAppendAccountIsNull() {
            addCriterion("appendAccount is null");
            return (Criteria) this;
        }

        public Criteria andAppendAccountIsNotNull() {
            addCriterion("appendAccount is not null");
            return (Criteria) this;
        }

        public Criteria andAppendAccountEqualTo(String value) {
            addCriterion("appendAccount =", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountNotEqualTo(String value) {
            addCriterion("appendAccount <>", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountGreaterThan(String value) {
            addCriterion("appendAccount >", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountGreaterThanOrEqualTo(String value) {
            addCriterion("appendAccount >=", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountLessThan(String value) {
            addCriterion("appendAccount <", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountLessThanOrEqualTo(String value) {
            addCriterion("appendAccount <=", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountLike(String value) {
            addCriterion("appendAccount like", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountNotLike(String value) {
            addCriterion("appendAccount not like", value, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountIn(List<String> values) {
            addCriterion("appendAccount in", values, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountNotIn(List<String> values) {
            addCriterion("appendAccount not in", values, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountBetween(String value1, String value2) {
            addCriterion("appendAccount between", value1, value2, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAppendAccountNotBetween(String value1, String value2) {
            addCriterion("appendAccount not between", value1, value2, "appendAccount");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppIsNull() {
            addCriterion("accountCodeOpp is null");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppIsNotNull() {
            addCriterion("accountCodeOpp is not null");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppEqualTo(String value) {
            addCriterion("accountCodeOpp =", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppNotEqualTo(String value) {
            addCriterion("accountCodeOpp <>", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppGreaterThan(String value) {
            addCriterion("accountCodeOpp >", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppGreaterThanOrEqualTo(String value) {
            addCriterion("accountCodeOpp >=", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppLessThan(String value) {
            addCriterion("accountCodeOpp <", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppLessThanOrEqualTo(String value) {
            addCriterion("accountCodeOpp <=", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppLike(String value) {
            addCriterion("accountCodeOpp like", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppNotLike(String value) {
            addCriterion("accountCodeOpp not like", value, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppIn(List<String> values) {
            addCriterion("accountCodeOpp in", values, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppNotIn(List<String> values) {
            addCriterion("accountCodeOpp not in", values, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppBetween(String value1, String value2) {
            addCriterion("accountCodeOpp between", value1, value2, "accountCodeOpp");
            return (Criteria) this;
        }

        public Criteria andAccountCodeOppNotBetween(String value1, String value2) {
            addCriterion("accountCodeOpp not between", value1, value2, "accountCodeOpp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f_summary
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 16 13:55:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table f_summary
     *
     * @mbg.generated Wed Aug 16 13:55:51 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}