package com.ifeng.bigtrade.finance.entites;

import java.util.Date;

public class FVoucherModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.id
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.addTime
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.deleteStatus
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private Boolean deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.modelCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private String modelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.modelName
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.creditCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.debitCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private String debitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.contractNo
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private String contractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.summary_id
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private Long summary_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_vouchermodel.note
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.id
     *
     * @return the value of f_vouchermodel.id
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.id
     *
     * @param id the value for f_vouchermodel.id
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.addTime
     *
     * @return the value of f_vouchermodel.addTime
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.addTime
     *
     * @param addTime the value for f_vouchermodel.addTime
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.deleteStatus
     *
     * @return the value of f_vouchermodel.deleteStatus
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.deleteStatus
     *
     * @param deleteStatus the value for f_vouchermodel.deleteStatus
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.modelCode
     *
     * @return the value of f_vouchermodel.modelCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.modelCode
     *
     * @param modelCode the value for f_vouchermodel.modelCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.modelName
     *
     * @return the value of f_vouchermodel.modelName
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.modelName
     *
     * @param modelName the value for f_vouchermodel.modelName
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.creditCode
     *
     * @return the value of f_vouchermodel.creditCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.creditCode
     *
     * @param creditCode the value for f_vouchermodel.creditCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.debitCode
     *
     * @return the value of f_vouchermodel.debitCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public String getDebitCode() {
        return debitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.debitCode
     *
     * @param debitCode the value for f_vouchermodel.debitCode
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setDebitCode(String debitCode) {
        this.debitCode = debitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.contractNo
     *
     * @return the value of f_vouchermodel.contractNo
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.contractNo
     *
     * @param contractNo the value for f_vouchermodel.contractNo
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.summary_id
     *
     * @return the value of f_vouchermodel.summary_id
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public Long getSummary_id() {
        return summary_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.summary_id
     *
     * @param summary_id the value for f_vouchermodel.summary_id
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setSummary_id(Long summary_id) {
        this.summary_id = summary_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_vouchermodel.note
     *
     * @return the value of f_vouchermodel.note
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_vouchermodel.note
     *
     * @param note the value for f_vouchermodel.note
     *
     * @mbg.generated Thu Aug 17 16:54:54 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }
}