package com.ifeng.bigtrade.purchasing.entites;

public class PFailedPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_failedplan.id
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_failedplan.issuanceplan_id
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    private Long issuanceplan_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_failedplan.operatorId
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_failedplan.operatorName
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_failedplan.operatorIp
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    private String operatorIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_failedplan.id
     *
     * @return the value of p_failedplan.id
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_failedplan.id
     *
     * @param id the value for p_failedplan.id
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_failedplan.issuanceplan_id
     *
     * @return the value of p_failedplan.issuanceplan_id
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public Long getIssuanceplan_id() {
        return issuanceplan_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_failedplan.issuanceplan_id
     *
     * @param issuanceplan_id the value for p_failedplan.issuanceplan_id
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public void setIssuanceplan_id(Long issuanceplan_id) {
        this.issuanceplan_id = issuanceplan_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_failedplan.operatorId
     *
     * @return the value of p_failedplan.operatorId
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_failedplan.operatorId
     *
     * @param operatorId the value for p_failedplan.operatorId
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_failedplan.operatorName
     *
     * @return the value of p_failedplan.operatorName
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_failedplan.operatorName
     *
     * @param operatorName the value for p_failedplan.operatorName
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_failedplan.operatorIp
     *
     * @return the value of p_failedplan.operatorIp
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_failedplan.operatorIp
     *
     * @param operatorIp the value for p_failedplan.operatorIp
     *
     * @mbg.generated Mon Sep 18 15:05:15 CST 2017
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp;
    }
}