package com.ifeng.bigtrade.purchasing.entites;

import java.util.Date;

public class PLotteryResultDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult_detail.id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult_detail.addTime
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult_detail.deleteStatus
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    private Boolean deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult_detail.issuanceplan_id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    private Long issuanceplan_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult_detail.winningNo
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    private String winningNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult_detail.applicationdetail_id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    private Long applicationdetail_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult_detail.id
     *
     * @return the value of p_lotteryresult_detail.id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult_detail.id
     *
     * @param id the value for p_lotteryresult_detail.id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult_detail.addTime
     *
     * @return the value of p_lotteryresult_detail.addTime
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult_detail.addTime
     *
     * @param addTime the value for p_lotteryresult_detail.addTime
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult_detail.deleteStatus
     *
     * @return the value of p_lotteryresult_detail.deleteStatus
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult_detail.deleteStatus
     *
     * @param deleteStatus the value for p_lotteryresult_detail.deleteStatus
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult_detail.issuanceplan_id
     *
     * @return the value of p_lotteryresult_detail.issuanceplan_id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public Long getIssuanceplan_id() {
        return issuanceplan_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult_detail.issuanceplan_id
     *
     * @param issuanceplan_id the value for p_lotteryresult_detail.issuanceplan_id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public void setIssuanceplan_id(Long issuanceplan_id) {
        this.issuanceplan_id = issuanceplan_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult_detail.winningNo
     *
     * @return the value of p_lotteryresult_detail.winningNo
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public String getWinningNo() {
        return winningNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult_detail.winningNo
     *
     * @param winningNo the value for p_lotteryresult_detail.winningNo
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public void setWinningNo(String winningNo) {
        this.winningNo = winningNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult_detail.applicationdetail_id
     *
     * @return the value of p_lotteryresult_detail.applicationdetail_id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public Long getApplicationdetail_id() {
        return applicationdetail_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult_detail.applicationdetail_id
     *
     * @param applicationdetail_id the value for p_lotteryresult_detail.applicationdetail_id
     *
     * @mbg.generated Tue Sep 12 13:39:42 CST 2017
     */
    public void setApplicationdetail_id(Long applicationdetail_id) {
        this.applicationdetail_id = applicationdetail_id;
    }
}