package com.ifeng.bigtrade.purchasing.entites;

import java.math.BigDecimal;
import java.util.Date;

public class PLotteryResult {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.id
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.addTime
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.deleteStatus
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private Boolean deleteStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.issuanceplan_id
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private Long issuanceplan_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.winningRate
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private BigDecimal winningRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.operatorId
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private Long operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.operatorName
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private String operatorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_lotteryresult.operatorIp
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	private String operatorIp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.id
	 * @return  the value of p_lotteryresult.id
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public Long getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.id
	 * @param id  the value for p_lotteryresult.id
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setId(Long id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.addTime
	 * @return  the value of p_lotteryresult.addTime
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public Date getAddTime()
	{
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.addTime
	 * @param addTime  the value for p_lotteryresult.addTime
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setAddTime(Date addTime)
	{
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.deleteStatus
	 * @return  the value of p_lotteryresult.deleteStatus
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public Boolean getDeleteStatus()
	{
		return deleteStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.deleteStatus
	 * @param deleteStatus  the value for p_lotteryresult.deleteStatus
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setDeleteStatus(Boolean deleteStatus)
	{
		this.deleteStatus = deleteStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.issuanceplan_id
	 * @return  the value of p_lotteryresult.issuanceplan_id
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public Long getIssuanceplan_id()
	{
		return issuanceplan_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.issuanceplan_id
	 * @param issuanceplan_id  the value for p_lotteryresult.issuanceplan_id
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setIssuanceplan_id(Long issuanceplan_id)
	{
		this.issuanceplan_id = issuanceplan_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.winningRate
	 * @return  the value of p_lotteryresult.winningRate
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public BigDecimal getWinningRate()
	{
		return winningRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.winningRate
	 * @param winningRate  the value for p_lotteryresult.winningRate
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setWinningRate(BigDecimal winningRate)
	{
		this.winningRate = winningRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.operatorId
	 * @return  the value of p_lotteryresult.operatorId
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public Long getOperatorId()
	{
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.operatorId
	 * @param operatorId  the value for p_lotteryresult.operatorId
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setOperatorId(Long operatorId)
	{
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.operatorName
	 * @return  the value of p_lotteryresult.operatorName
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public String getOperatorName()
	{
		return operatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.operatorName
	 * @param operatorName  the value for p_lotteryresult.operatorName
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setOperatorName(String operatorName)
	{
		this.operatorName = operatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_lotteryresult.operatorIp
	 * @return  the value of p_lotteryresult.operatorIp
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public String getOperatorIp()
	{
		return operatorIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_lotteryresult.operatorIp
	 * @param operatorIp  the value for p_lotteryresult.operatorIp
	 * @mbg.generated  Wed Sep 20 18:03:16 CST 2017
	 */
	public void setOperatorIp(String operatorIp)
	{
		this.operatorIp = operatorIp;
	}
}