package com.ifeng.bigtrade.purchasing.entites;

public class PLotteryResultWithBLOBs extends PLotteryResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult.lotteryResult
     *
     * @mbg.generated Wed Sep 20 18:03:16 CST 2017
     */
    private String lotteryResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_lotteryresult.lotteryResultShow
     *
     * @mbg.generated Wed Sep 20 18:03:16 CST 2017
     */
    private String lotteryResultShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult.lotteryResult
     *
     * @return the value of p_lotteryresult.lotteryResult
     *
     * @mbg.generated Wed Sep 20 18:03:16 CST 2017
     */
    public String getLotteryResult() {
        return lotteryResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult.lotteryResult
     *
     * @param lotteryResult the value for p_lotteryresult.lotteryResult
     *
     * @mbg.generated Wed Sep 20 18:03:16 CST 2017
     */
    public void setLotteryResult(String lotteryResult) {
        this.lotteryResult = lotteryResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_lotteryresult.lotteryResultShow
     *
     * @return the value of p_lotteryresult.lotteryResultShow
     *
     * @mbg.generated Wed Sep 20 18:03:16 CST 2017
     */
    public String getLotteryResultShow() {
        return lotteryResultShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_lotteryresult.lotteryResultShow
     *
     * @param lotteryResultShow the value for p_lotteryresult.lotteryResultShow
     *
     * @mbg.generated Wed Sep 20 18:03:16 CST 2017
     */
    public void setLotteryResultShow(String lotteryResultShow) {
        this.lotteryResultShow = lotteryResultShow;
    }
}