package com.ifeng.bigtrade.finance.mapper;

import com.ifeng.bigtrade.finance.entites.FSummary;
import com.ifeng.bigtrade.finance.entites.FSummaryExample.Criteria;
import com.ifeng.bigtrade.finance.entites.FSummaryExample.Criterion;
import com.ifeng.bigtrade.finance.tools.CommUtil;
import com.ifeng.bigtrade.finance.entites.FSummaryExample;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class FSummarySqlProvider
{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String countByExample(FSummaryExample example)
	{
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("f_summary");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String deleteByExample(FSummaryExample example)
	{
		SQL sql = new SQL();
		sql.DELETE_FROM("f_summary");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String insertSelective(FSummary record)
	{
		SQL sql = new SQL();
		sql.INSERT_INTO("f_summary");

		if (record.getId() != null)
		{
			sql.VALUES("id", "#{id,jdbcType=BIGINT}");
		}

		if (record.getAddTime() != null)
		{
			sql.VALUES("addTime", "#{addTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteStatus() != null)
		{
			sql.VALUES("deleteStatus", "#{deleteStatus,jdbcType=BIT}");
		}

		if (record.getCanDelete() != null)
		{
			sql.VALUES("canDelete", "#{canDelete,jdbcType=BIT}");
		}

		if (record.getIsUserFunds() != null)
		{
			sql.VALUES("isUserFunds", "#{isUserFunds,jdbcType=BIT}");
		}

		if (record.getSummary() != null)
		{
			sql.VALUES("summary", "#{summary,jdbcType=VARCHAR}");
		}

		if (record.getSummaryNo() != null)
		{
			sql.VALUES("summaryNo", "#{summaryNo,jdbcType=VARCHAR}");
		}

		if (record.getLedger_id() != null)
		{
			sql.VALUES("ledger_id", "#{ledger_id,jdbcType=BIGINT}");
		}

		if (record.getFundDCFlag() != null)
		{
			sql.VALUES("fundDCFlag", "#{fundDCFlag,jdbcType=VARCHAR}");
		}

		if (record.getAppendAccount() != null)
		{
			sql.VALUES("appendAccount", "#{appendAccount,jdbcType=VARCHAR}");
		}

		if (record.getAccountCodeOpp() != null)
		{
			sql.VALUES("accountCodeOpp", "#{accountCodeOpp,jdbcType=VARCHAR}");
		}

		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String selectByExample(FSummaryExample example)
	{
		SQL sql = new SQL();
		if (example != null && example.isDistinct())
		{
			sql.SELECT_DISTINCT("id");
		} else
		{
			sql.SELECT("id");
		}
		sql.SELECT("addTime");
		sql.SELECT("deleteStatus");
		sql.SELECT("canDelete");
		sql.SELECT("isUserFunds");
		sql.SELECT("summary");
		sql.SELECT("summaryNo");
		sql.SELECT("ledger_id");
		sql.SELECT("fundDCFlag");
		sql.SELECT("appendAccount");
		sql.SELECT("accountCodeOpp");
		sql.FROM("f_summary");
		applyWhere(sql, example, false);

		if (example != null && example.getOrderByClause() != null)
		{
			sql.ORDER_BY(example.getOrderByClause());
		}

		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String updateByExampleSelective(Map<String, Object> parameter)
	{
		FSummary record = (FSummary) parameter.get("record");
		FSummaryExample example = (FSummaryExample) parameter.get("example");

		SQL sql = new SQL();
		sql.UPDATE("f_summary");

		if (record.getId() != null)
		{
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}

		if (record.getAddTime() != null)
		{
			sql.SET("addTime = #{record.addTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteStatus() != null)
		{
			sql.SET("deleteStatus = #{record.deleteStatus,jdbcType=BIT}");
		}

		if (record.getCanDelete() != null)
		{
			sql.SET("canDelete = #{record.canDelete,jdbcType=BIT}");
		}

		if (record.getIsUserFunds() != null)
		{
			sql.SET("isUserFunds = #{record.isUserFunds,jdbcType=BIT}");
		}

		if (record.getSummary() != null)
		{
			sql.SET("summary = #{record.summary,jdbcType=VARCHAR}");
		}

		if (record.getSummaryNo() != null)
		{
			sql.SET("summaryNo = #{record.summaryNo,jdbcType=VARCHAR}");
		}

		if (record.getLedger_id() != null)
		{
			sql.SET("ledger_id = #{record.ledger_id,jdbcType=BIGINT}");
		}

		if (record.getFundDCFlag() != null)
		{
			sql.SET("fundDCFlag = #{record.fundDCFlag,jdbcType=VARCHAR}");
		}

		if (record.getAppendAccount() != null)
		{
			sql.SET("appendAccount = #{record.appendAccount,jdbcType=VARCHAR}");
		}

		if (record.getAccountCodeOpp() != null)
		{
			sql.SET("accountCodeOpp = #{record.accountCodeOpp,jdbcType=VARCHAR}");
		}

		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String updateByExample(Map<String, Object> parameter)
	{
		SQL sql = new SQL();
		sql.UPDATE("f_summary");

		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("addTime = #{record.addTime,jdbcType=TIMESTAMP}");
		sql.SET("deleteStatus = #{record.deleteStatus,jdbcType=BIT}");
		sql.SET("canDelete = #{record.canDelete,jdbcType=BIT}");
		sql.SET("isUserFunds = #{record.isUserFunds,jdbcType=BIT}");
		sql.SET("summary = #{record.summary,jdbcType=VARCHAR}");
		sql.SET("summaryNo = #{record.summaryNo,jdbcType=VARCHAR}");
		sql.SET("ledger_id = #{record.ledger_id,jdbcType=BIGINT}");
		sql.SET("fundDCFlag = #{record.fundDCFlag,jdbcType=VARCHAR}");
		sql.SET("appendAccount = #{record.appendAccount,jdbcType=VARCHAR}");
		sql.SET("accountCodeOpp = #{record.accountCodeOpp,jdbcType=VARCHAR}");

		FSummaryExample example = (FSummaryExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	public String updateByPrimaryKeySelective(FSummary record)
	{
		SQL sql = new SQL();
		sql.UPDATE("f_summary");

		if (record.getAddTime() != null)
		{
			sql.SET("addTime = #{addTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteStatus() != null)
		{
			sql.SET("deleteStatus = #{deleteStatus,jdbcType=BIT}");
		}

		if (record.getCanDelete() != null)
		{
			sql.SET("canDelete = #{canDelete,jdbcType=BIT}");
		}

		if (record.getIsUserFunds() != null)
		{
			sql.SET("isUserFunds = #{isUserFunds,jdbcType=BIT}");
		}

		if (record.getSummary() != null)
		{
			sql.SET("summary = #{summary,jdbcType=VARCHAR}");
		}

		if (record.getSummaryNo() != null)
		{
			sql.SET("summaryNo = #{summaryNo,jdbcType=VARCHAR}");
		}

		if (record.getLedger_id() != null)
		{
			sql.SET("ledger_id = #{ledger_id,jdbcType=BIGINT}");
		}

		if (record.getFundDCFlag() != null)
		{
			sql.SET("fundDCFlag = #{fundDCFlag,jdbcType=VARCHAR}");
		}

		if (record.getAppendAccount() != null)
		{
			sql.SET("appendAccount = #{appendAccount,jdbcType=VARCHAR}");
		}

		if (record.getAccountCodeOpp() != null)
		{
			sql.SET("accountCodeOpp = #{accountCodeOpp,jdbcType=VARCHAR}");
		}

		sql.WHERE("id = #{id,jdbcType=BIGINT}");

		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table f_summary
	 *
	 * @mbg.generated Wed Aug 16 13:55:51 CST 2017
	 */
	protected void applyWhere(SQL sql, FSummaryExample example, boolean includeExamplePhrase)
	{
		if (example == null)
		{
			return;
		}

		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase)
		{
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else
		{
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}

		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++)
		{
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid())
			{
				if (firstCriteria)
				{
					firstCriteria = false;
				} else
				{
					sb.append(" or ");
				}

				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++)
				{
					Criterion criterion = criterions.get(j);
					if (firstCriterion)
					{
						firstCriterion = false;
					} else
					{
						sb.append(" and ");
					}

					if (criterion.isNoValue())
					{
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue())
					{
						if (criterion.getTypeHandler() == null)
						{
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else
						{
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue())
					{
						if (criterion.getTypeHandler() == null)
						{
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else
						{
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue())
					{
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++)
						{
							if (comma)
							{
								sb.append(", ");
							} else
							{
								comma = true;
							}
							if (criterion.getTypeHandler() == null)
							{
								sb.append(String.format(parmPhrase3, i, j, k));
							} else
							{
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}

		if (sb.length() > 0)
		{
			sql.WHERE(sb.toString());
		}
	}

	/******************** next new add ************************/
	/**
	 * 查询摘要列表
	 * 
	 * @param systemid 关联到ledgerfield的系统号
	 * @param summaryno 摘要号
	 * @param order 排序字段
	 * @return
	 */
	public String selectSummary(String systemid, String summaryno)
	{
		SQL sql = new SQL();
		sql.SELECT("s.*,l.systemid").FROM("f_summary s,f_ledgerfield l").WHERE("s.ledger_id=l.id");
		if (CommUtil.isNotNull(systemid))
		{
			sql.WHERE("systemid = '" + systemid + "'");
		}
		if (CommUtil.isNotNull(summaryno))
		{
			sql.WHERE("summaryNo = '" + summaryno + "'");
		}
		return sql.toString();
	}
}